### ISSUE TITLE
guildMemberAdd question

### ISSUE THREAD

**Issue by Owned67** [Sworder71/tuto-discord-BOT#2]
Bonjour,

peut t'on mettre un message avec embed dans un fichier .json ?

 `await member.guild.channels.get(channel).send({"embed": {
color: 3447003,
author: {
  name: client.user.username,
  icon_url: client.user.avatarURL
},
title: "Bienvenue !",
url: "http://test.fr/",
description: "@MEMBER",
fields: [{
  name: "RÃ¨gles :",
    value: "Bienvenue  ${member}, voici quelques rÃ¨gles Ã  respecter :  \n \n \
	1)- les insultes, propos racistes, homophobes sont interdites Â¹ \n \
	2)- Si jamais vous avez un problÃ¨me extÃ©rieur au serveur ce n'est en aucun cas notre problÃ¨me, cela reste en conversation privÃ©e. \n \
	3)- Le respect est bÃ©nÃ©fique au bon fonctionnement et la bonne entente, donc respectez-vous. \n \
	4)- Pour des questions, des demandes oÃ¹ tout autre problÃ¨me, contactez un membre du staff. \n \
	5)- Merci de poster dans les channels appropriÃ©s"
  },
  {
	name: "Groupe Steam:",
    value: "https://steamcommunity.com/groups/test"
  }
],
timestamp: new Date(),
footer: {
  icon_url: client.user.avatarURL,
  text: "NomadesRust - 2019"
}
}});`

Je débute en programmation..

Merci pour ton aide

Je ne suis pas copain avec l'anglais donc désolé de te contacter pour ceci...

**Comment by Sworder71** [comment]
> peut t'on mettre un message avec embed dans un fichier .json ?

Salut, c'est à dire ?

**Comment by Owned67** [comment]
On ne peut pas, faut utiliser un .js, j'ai trouvé la réponse ^^
